services:
  formodoro:
    build: .
    container_name: formodoro
    ports:
      - "28100:8000"
    environment:
      DB_IMPLEMENTATION: tinydb
      TINYDB_TABLE: mytable
      CORS_ORIGINS: http://localhost:8080 # Adjust this to your frontend URL, comma-separated if needed
      RATELIMIT: 5/minute
      # NOTIFIERS_PROVIDER: e.g. telegram (optional)
      # other notifiers environment variables
      # see https://notifiers.readthedocs.io/en/latest/usage.html#environment-variables
    volumes:
      - ./tinydb:/tinydb
