services:
  formodoro:
    build: .
    container_name: formodoro
    ports:
      - "28100:8000"
    environment:
      MONGODB_URL: mongodb://admin:password@mongo:27017
      MONGODB_DB: mydatabase
      MONGODB_COLLECTION: mycollection
      CORS_ORIGINS: http://localhost:8080 # Adjust this to your frontend URL, comma-separated if needed
      RATELIMIT: 5/minute
      # NOTIFIERS_PROVIDER: e.g. telegram (optional)
      # other notifiers environment variables
      # see https://notifiers.readthedocs.io/en/latest/usage.html#environment-variables
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
